export const accessoryProductsData = [
  {
    name: "Leather Handbag",
    slug: "leather-handbag",
    description: "Elegant leather handbag with adjustable strap.",
    originalPrice: 149.99,
    currentPrice: 149.99,
    mainImage: "05344205051-e1_x4elaf",
    images: ["accessories/handbag-2"],
    colors: ["Black", "Brown", "Tan"],
    sizes: ["One Size"],
    quantity: 20,
    sku: "AH001",
    tags: ["handbag", "leather", "elegant"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Silk Scarf",
    slug: "silk-scarf",
    description: "Luxurious silk scarf with artistic print.",
    originalPrice: 79.99,
    currentPrice: 59.99,
    discountPercent: 25.0,
    mainImage: "05919330800-e1_ttunjm",
    images: ["accessories/scarf-2"],
    colors: ["Multi", "Blue", "Red"],
    sizes: ["One Size"],
    quantity: 15,
    onSale: true,
    sku: "AS001",
    tags: ["scarf", "silk", "luxurious"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Classic Watch",
    slug: "classic-watch",
    description: "Minimalist watch with leather strap.",
    originalPrice: 199.99,
    currentPrice: 199.99,
    mainImage: "00653231707-p_pluldk",
    images: ["accessories/watch-2"],
    colors: ["Black", "Brown"],
    sizes: ["One Size"],
    quantity: 12,
    isFeatured: true,
    sku: "AW001",
    tags: ["watch", "classic", "minimalist"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Canvas Tote Bag",
    slug: "canvas-tote-bag",
    description: "Eco-friendly canvas tote with printed design.",
    originalPrice: 29.99,
    currentPrice: 29.99,
    mainImage: "04548264881-p_wbgqmd",
    images: ["accessories/tote-2"],
    colors: ["Natural", "Black", "Olive"],
    sizes: ["One Size"],
    quantity: 40,
    sku: "AT001",
    tags: ["tote", "canvas", "eco"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Geometric Sunglasses",
    slug: "geometric-sunglasses",
    description: "Bold sunglasses with geometric frames and UV protection.",
    originalPrice: 69.99,
    currentPrice: 69.99,
    mainImage: "02907302800-a3_ufwpds",
    images: ["accessories/sunglasses-2"],
    colors: ["Black", "Tortoise", "Clear"],
    sizes: ["One Size"],
    quantity: 25,
    sku: "AG001",
    tags: ["sunglasses", "geometric", "bold"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Wool Beanie",
    slug: "wool-beanie",
    description: "Soft wool beanie with ribbed texture.",
    originalPrice: 24.99,
    currentPrice: 24.99,
    mainImage: "03920204051-e1_sqmtyh",
    images: ["accessories/beanie-2"],
    colors: ["Grey", "Navy", "Burgundy"],
    sizes: ["One Size"],
    quantity: 30,
    sku: "AB001",
    tags: ["beanie", "wool", "winter"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Minimalist Belt",
    slug: "minimalist-belt",
    description: "Slim leather belt with matte buckle.",
    originalPrice: 49.99,
    currentPrice: 49.99,
    mainImage: "02750400760-a3_u94dtz",
    images: ["accessories/belt-2"],
    colors: ["Black", "Tan"],
    sizes: ["S", "M", "L"],
    quantity: 18,
    sku: "ABL001",
    tags: ["belt", "minimalist", "leather"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Pearl Hair Clip Set",
    slug: "pearl-hair-clip-set",
    description: "Set of 3 pearl-embellished hair clips.",
    originalPrice: 19.99,
    currentPrice: 19.99,
    mainImage: "01023254707-p_agputv",
    images: ["accessories/hair-clips-2"],
    colors: ["White", "Gold"],
    sizes: ["One Size"],
    quantity: 50,
    sku: "AHC001",
    tags: ["hair", "clip", "pearl"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Travel Jewelry Case",
    slug: "travel-jewelry-case",
    description: "Compact jewelry case with velvet lining and mirror.",
    originalPrice: 39.99,
    currentPrice: 39.99,
    mainImage: "01011269807-p_jhm7za",
    images: ["accessories/jewelry-case-2"],
    colors: ["Blush", "Ivory", "Mint"],
    sizes: ["One Size"],
    quantity: 22,
    sku: "AJC001",
    tags: ["jewelry", "case", "travel"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Tech Organizer Pouch",
    slug: "tech-organizer-pouch",
    description: "Multi-compartment pouch for cables, chargers, and accessories.",
    originalPrice: 34.99,
    currentPrice: 34.99,
    mainImage: "01011277303-e1_dgl9gn",
    images: ["accessories/tech-pouch-2"],
    colors: ["Grey", "Black", "Navy"],
    sizes: ["One Size"],
    quantity: 28,
    sku: "ATP001",
    tags: ["tech", "organizer", "pouch"],
    currency: "USD",
    inStock: true
  }
];