export const kidsProductsData = [
  {
    name: "Colorblock Puffer Jacket",
    slug: "colorblock-puffer-jacket",
    description: "Warm puffer jacket with bold color panels and fleece-lined hood.",
    originalPrice: 89.99,
    currentPrice: 89.99,
    mainImage: "06061587619-e1_r96cce",
    images: ["kids/colorblock-jacket-2"],
    colors: ["Red/Navy", "Pink/Teal", "Green/Yellow"],
    sizes: ["XS", "S", "M", "L"],
    quantity: 15,
    isFeatured: true,
    sku: "KJ001",
    tags: ["jacket", "puffer", "colorblock", "winter"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Stretch Denim Joggers",
    slug: "stretch-denim-joggers",
    description: "Soft denim joggers with elastic waistband and tapered fit.",
    originalPrice: 39.99,
    currentPrice: 39.99,
    mainImage: "05644702626-e1_dyfqmh",
    images: ["kids/denim-joggers-2"],
    colors: ["Light Wash", "Dark Wash"],
    sizes: ["4", "6", "8", "10", "12"],
    quantity: 20,
    sku: "KP001",
    tags: ["pants", "denim", "joggers", "stretch"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Graphic Long Sleeve Tee",
    slug: "graphic-long-sleeve-tee",
    description: "Cotton tee with fun animal prints and ribbed cuffs.",
    originalPrice: 24.99,
    currentPrice: 24.99,
    mainImage: "05431782712-e1_j4hkaf",
    images: ["kids/graphic-tee-2"],
    colors: ["White", "Blue", "Lavender"],
    sizes: ["XS", "S", "M", "L"],
    quantity: 25,
    isNew: true,
    sku: "KT001",
    tags: ["tshirt", "graphic", "animals", "cotton"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Corduroy Overalls",
    slug: "corduroy-overalls",
    description: "Classic overalls in soft corduroy with adjustable straps.",
    originalPrice: 49.99,
    currentPrice: 49.99,
    mainImage: "05431741812-e1_y2jjcx",
    images: ["kids/corduroy-overalls-2"],
    colors: ["Rust", "Olive", "Navy"],
    sizes: ["2T", "3T", "4T", "5T"],
    quantity: 12,
    sku: "KO001",
    tags: ["overalls", "corduroy", "classic", "toddler"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Velcro High-Top Sneakers",
    slug: "velcro-high-top-sneakers",
    description: "Easy-on sneakers with padded ankle and playful colorways.",
    originalPrice: 59.99,
    currentPrice: 59.99,
    mainImage: "05059700400-e1_h4t4f1",
    images: ["kids/high-top-sneakers-2"],
    colors: ["White/Blue", "Pink/Yellow", "Black/Green"],
    sizes: ["10", "11", "12", "13", "1", "2"],
    quantity: 18,
    sku: "KS001",
    tags: ["sneakers", "velcro", "high-top", "kids"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Rainbow Knit Sweater",
    slug: "rainbow-knit-sweater",
    description: "Chunky knit sweater with rainbow stripes and ribbed trim.",
    originalPrice: 44.99,
    currentPrice: 44.99,
    mainImage: "04320700807-e1_yhckum",
    images: ["kids/rainbow-sweater-2"],
    colors: ["Multi", "Pastel", "Bold"],
    sizes: ["XS", "S", "M", "L"],
    quantity: 14,
    sku: "KSW001",
    tags: ["sweater", "knit", "rainbow", "cozy"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Playtime Cargo Shorts",
    slug: "playtime-cargo-shorts",
    description: "Durable cargo shorts with elastic waist and side pockets.",
    originalPrice: 29.99,
    currentPrice: 29.99,
    mainImage: "01277704898-e1_qampm1",
    images: ["kids/cargo-shorts-2"],
    colors: ["Khaki", "Navy", "Olive"],
    sizes: ["4", "6", "8", "10"],
    quantity: 22,
    sku: "KCS001",
    tags: ["shorts", "cargo", "playtime", "durable"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Twirl Tulle Skirt",
    slug: "twirl-tulle-skirt",
    description: "Layered tulle skirt with elastic waistband and glitter accents.",
    originalPrice: 34.99,
    currentPrice: 34.99,
    mainImage: "00673704800-e1_yhvnoe",
    images: ["kids/tulle-skirt-2"],
    colors: ["Pink", "Lilac", "Mint"],
    sizes: ["XS", "S", "M"],
    quantity: 10,
    sku: "KTS001",
    tags: ["skirt", "tulle", "twirl", "glitter"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Dino Print Pajama Set",
    slug: "dino-print-pajama-set",
    description: "Soft cotton pajama set with glow-in-the-dark dinosaur graphics.",
    originalPrice: 27.99,
    currentPrice: 27.99,
    mainImage: "00257708926-e1_jgwfvm",
    images: ["kids/dino-pajamas-2"],
    colors: ["Green", "Blue", "Grey"],
    sizes: ["2T", "3T", "4T", "5T", "6"],
    quantity: 30,
    sku: "KPJ001",
    tags: ["pajamas", "dino", "glow", "cotton"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Sunshine Bucket Hat",
    slug: "sunshine-bucket-hat",
    description: "Lightweight bucket hat with UV protection and fun prints.",
    originalPrice: 19.99,
    currentPrice: 19.99,
    mainImage: "00257708526-e1_mnouim",
    images: ["kids/bucket-hat-2"],
    colors: ["Yellow", "Sky Blue", "Coral"],
    sizes: ["S", "M"],
    quantity: 35,
    sku: "KBH001",
    tags: ["hat", "bucket", "sun", "UV"],
    currency: "USD",
    inStock: true
  }
];
