export const menProductsData = [
  {
    name: "Oversized Wool Coat",
    slug: "oversized-wool-coat",
    description: "Relaxed-fit wool coat with dropped shoulders and minimalist lapels.",
    originalPrice: 229.99,
    currentPrice: 229.99,
    mainImage: "09621160800-a3_faaksv",
    images: ["men/wool-coat-2"],
    colors: ["Camel", "Charcoal", "Taupe"],
    sizes: ["S", "M", "L", "XL"],
    quantity: 12,
    isFeatured: true,
    sku: "MWC001",
    tags: ["coat", "wool", "oversized", "minimalist"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Cropped Pleated Trousers",
    slug: "cropped-pleated-trousers",
    description: "Tailored cropped trousers with front pleats and ankle length.",
    originalPrice: 79.99,
    currentPrice: 79.99,
    mainImage: "07446311055-p_dfoppv",
    images: ["men/cropped-trousers-2"],
    colors: ["Stone", "Olive", "Black"],
    sizes: ["30", "32", "34", "36"],
    quantity: 18,
    sku: "MPT001",
    tags: ["trousers", "cropped", "pleated", "tailored"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Boxy Fit T-Shirt",
    slug: "boxy-fit-tshirt",
    description: "Heavyweight cotton T-shirt with wide sleeves and relaxed silhouette.",
    originalPrice: 39.99,
    currentPrice: 39.99,
    mainImage: "06917303250-p_diuec2",
    images: ["men/boxy-tshirt-2"],
    colors: ["Off-white", "Sage", "Rust"],
    sizes: ["S", "M", "L", "XL"],
    quantity: 30,
    isNew: true,
    sku: "MBT001",
    tags: ["tshirt", "boxy", "streetwear", "cotton"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Textured Knit Polo",
    slug: "textured-knit-polo",
    description: "Retro-inspired knit polo with waffle texture and open collar.",
    originalPrice: 59.99,
    currentPrice: 59.99,
    mainImage: "06224386803-p_md7qtq",
    images: ["men/knit-polo-2"],
    colors: ["Mustard", "Navy", "Cream"],
    sizes: ["S", "M", "L", "XL"],
    quantity: 22,
    sku: "MKP001",
    tags: ["polo", "knit", "retro", "textured"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Nylon Utility Vest",
    slug: "nylon-utility-vest",
    description: "Lightweight utility vest with multiple pockets and zip closure.",
    originalPrice: 69.99,
    currentPrice: 69.99,
    mainImage: "04426909081-p_sxnu4q",
    images: ["men/utility-vest-2"],
    colors: ["Black", "Khaki", "Graphite"],
    sizes: ["S", "M", "L"],
    quantity: 16,
    sku: "MUV001",
    tags: ["vest", "utility", "techwear", "nylon"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Chunky Sole Sneakers",
    slug: "chunky-sole-sneakers",
    description: "Bold sneakers with mixed materials and exaggerated sole design.",
    originalPrice: 119.99,
    currentPrice: 119.99,
    mainImage: "04365350800-p_jw5ni9",
    images: ["men/chunky-sneakers-2"],
    colors: ["White/Beige", "Grey/Neon", "Black/Red"],
    sizes: ["40", "41", "42", "43", "44"],
    quantity: 25,
    sku: "MCS001",
    tags: ["sneakers", "chunky", "futuristic", "bold"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Linen Blend Mandarin Shirt",
    slug: "linen-mandarin-shirt",
    description: "Breathable linen blend shirt with a collarless mandarin neckline.",
    originalPrice: 49.99,
    currentPrice: 49.99,
    mainImage: "04092360800-p_d7fmp6",
    images: ["men/mandarin-shirt-2"],
    colors: ["Sand", "Sky Blue", "Olive"],
    sizes: ["S", "M", "L", "XL"],
    quantity: 20,
    sku: "MLS001",
    tags: ["shirt", "linen", "mandarin", "summer"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Faux Suede Bomber Jacket",
    slug: "faux-suede-bomber-jacket",
    description: "Soft-touch bomber jacket in faux suede with ribbed cuffs.",
    originalPrice: 109.99,
    currentPrice: 109.99,
    mainImage: "04087321712-p_fgujf7",
    images: ["men/suede-bomber-2"],
    colors: ["Mocha", "Slate", "Burgundy"],
    sizes: ["S", "M", "L", "XL"],
    quantity: 14,
    sku: "MSB001",
    tags: ["jacket", "bomber", "suede", "soft-touch"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Monochrome Co-ord Set",
    slug: "monochrome-coord-set",
    description: "Minimalist co-ord set with matching shirt and trousers.",
    originalPrice: 139.99,
    currentPrice: 139.99,
    mainImage: "03918360500-p_o6vgpw",
    images: ["men/coord-set-2"],
    colors: ["Black", "Beige", "Grey"],
    sizes: ["S", "M", "L", "XL"],
    quantity: 10,
    sku: "MCS002",
    tags: ["coord", "minimalist", "set", "monochrome"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Turtleneck with Side Zipper",
    slug: "turtleneck-side-zipper",
    description: "Slim-fit turtleneck with asymmetric side zipper detail.",
    originalPrice: 69.99,
    currentPrice: 69.99,
    mainImage: "02878304800-p_wcugzw",
    images: ["men/turtleneck-zipper-2"],
    colors: ["Charcoal", "Forest Green", "Cream"],
    sizes: ["S", "M", "L", "XL"],
    quantity: 17,
    sku: "MTZ001",
    tags: ["turtleneck", "zipper", "slim-fit", "elevated"],
    currency: "USD",
    inStock: true
  }
];
