export const womenProductsData = [
  {
    name: "Oversized Denim Jacket",
    slug: "oversized-denim-jacket",
    description: "Comfortable oversized denim jacket with a relaxed fit. Perfect for layering in transitional weather.",
    originalPrice: 89.99,
    currentPrice: 89.99,
    mainImage: "05919208800-p_y9uq4m",
    images: ["women/denim-jacket-2", "women/denim-jacket-3"],
    colors: ["Blue", "Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    quantity: 25,
    isNew: true,
    sku: "WJ001",
    tags: ["jacket", "denim", "oversized"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Leather Biker Jacket",
    slug: "leather-biker-jacket",
    description: "Classic biker jacket made from premium faux leather with zipper details.",
    originalPrice: 159.99,
    currentPrice: 129.99,
    discountPercent: 18.75,
    mainImage: "01478152700-p_uyx6lq",
    images: ["women/leather-jacket-2"],
    colors: ["Black", "Brown"],
    sizes: ["S", "M", "L"],
    quantity: 18,
    onSale: true,
    sku: "WJ002",
    tags: ["jacket", "leather", "biker"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Silk Blend Blouse",
    slug: "silk-blend-blouse",
    description: "Elegant silk blend blouse with a delicate pattern and button-down front.",
    originalPrice: 59.99,
    currentPrice: 59.99,
    mainImage: "02753630052-p_vowowq",
    images: ["women/blouse-2"],
    colors: ["White", "Cream", "Navy"],
    sizes: ["XS", "S", "M", "L"],
    quantity: 32,
    isNew: true,
    sku: "WB001",
    tags: ["blouse", "silk", "elegant"],
    currency: "USD",
    inStock: true
  },
  {
    name: "High-Waisted Trousers",
    slug: "high-waisted-trousers",
    description: "Tailored high-waisted trousers with a slim fit and straight leg.",
    originalPrice: 79.99,
    currentPrice: 79.99,
    mainImage: "01255717684-p_u68vgk",
    images: ["women/trousers-2"],
    colors: ["Black", "Navy", "Beige"],
    sizes: ["XS", "S", "M", "L", "XL"],
    quantity: 20,
    sku: "WT001",
    tags: ["trousers", "high-waisted", "tailored"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Knit Sweater Dress",
    slug: "knit-sweater-dress",
    description: "Cozy knit sweater dress with ribbed details and a relaxed fit.",
    originalPrice: 69.99,
    currentPrice: 69.99,
    mainImage: "02753122700-p_twn38x",
    images: ["women/dress-2"],
    colors: ["Cream", "Grey", "Burgundy"],
    sizes: ["S", "M", "L"],
    quantity: 15,
    isNew: true,
    isFeatured: true,
    sku: "WD001",
    tags: ["dress", "knit", "sweater"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Wool Blend Coat",
    slug: "wool-blend-coat",
    description: "Warm wool blend coat with a double-breasted front and notched lapel.",
    originalPrice: 249.99,
    currentPrice: 199.99,
    discountPercent: 20.0,
    mainImage: "02183245832-p_soptxr",
    images: ["women/coat-2"],
    colors: ["Camel", "Black", "Grey"],
    sizes: ["S", "M", "L", "XL"],
    quantity: 12,
    onSale: true,
    sku: "WC001",
    tags: ["coat", "wool", "warm"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Linen Blend Shirt",
    slug: "linen-blend-shirt",
    description: "Breathable linen blend shirt with a relaxed fit and roll-up sleeves.",
    originalPrice: 49.99,
    currentPrice: 49.99,
    mainImage: "08851171717-p_dcvj2d",
    images: ["women/shirt-2"],
    colors: ["White", "Blue", "Green"],
    sizes: ["XS", "S", "M", "L"],
    quantity: 28,
    sku: "WS001",
    tags: ["shirt", "linen", "breathable"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Midi Skirt with Slit",
    slug: "midi-skirt-with-slit",
    description: "Elegant midi skirt with a side slit and flowing silhouette.",
    originalPrice: 65.99,
    currentPrice: 65.99,
    mainImage: "03046273710-p_irk2s7",
    images: ["women/skirt-2"],
    colors: ["Black", "Navy", "Burgundy"],
    sizes: ["XS", "S", "M", "L"],
    quantity: 22,
    isNew: true,
    sku: "WSK001",
    tags: ["skirt", "midi", "elegant"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Faux Leather Pants",
    slug: "faux-leather-pants",
    description: "Stylish faux leather pants with a slim fit and high waist.",
    originalPrice: 99.99,
    currentPrice: 89.99,
    discountPercent: 10.0,
    mainImage: "05919241450-a3_p65vrt",
    images: ["women/pants-2"],
    colors: ["Black", "Brown"],
    sizes: ["XS", "S", "M", "L"],
    quantity: 17,
    onSale: true,
    sku: "WP001",
    tags: ["pants", "leather", "stylish"],
    currency: "USD",
    inStock: true
  },
  {
    name: "Cashmere Blend Sweater",
    slug: "cashmere-blend-sweater",
    description: "Luxurious cashmere blend sweater with a relaxed fit and ribbed cuffs.",
    originalPrice: 129.99,
    currentPrice: 129.99,
    mainImage: "08484438422-a1_wf95oy",
    images: ["women/sweater-2"],
    colors: ["Grey", "Cream", "Navy"],
    sizes: ["XS", "S", "M", "L", "XL"],
    quantity: 30,
    isNew: true,
    isFeatured: true,
    sku: "WSW001",
    tags: ["sweater", "cashmere", "luxurious"],
    currency: "USD",
    inStock: true
  }
];